"use client";
import { useState } from "react";
import { money, money2, num, fDate, fDT } from "@vivaha/shared";
import { useApi, useLines, refresh } from "@/lib/hooks";
import { useAuth } from "@/lib/auth-context";
import { useUI, errMsg } from "@/lib/ui";
import { post, put, del } from "@/lib/api";
import { Pill, DF, Section, DrawerFrame, ModalFrame, Field, Note, Bar, Timeline } from "./ui";
import type { Customer, ItemView } from "./types";

const SPEC: Record<string, string> = { colours: "Colours", ink: "Ink brand", company: "Machine company", roller: "Roller cloth", chem: "Chemicals brand", industry: "Industry", model: "Model" };
type Full = Customer & { multiplier: number; outstanding: number; statement: { id: string; date: string; particular: string; debit: number; credit: number; bal: number }[]; ageing: { buckets: number[]; labels: string[] }; orders: { id: string; total: number; status: string; createdAt: string }[]; overrides: { itemId: string; sku: string; name: string; rate: number; slabRate: number; groupRate: number; floor: number }[] };

export function CustomerDrawer({ id }: { id: string }) {
  const { data: c } = useApi<Full>(`/api/customers/${id}`); const { closeDrawer, openModal, toast } = useUI(); const { can } = useAuth(); const { data: lines } = useLines();
  if (!c) return <div className="drb"><div className="sm">Loading…</div></div>;
  const g = c.gate, a = c.ageing;
  const unblock = async () => { try { await post(`/api/customers/${id}/unblock`); toast("Block lifted", "s"); closeDrawer(); refresh("/api/"); } catch (e) { toast(errMsg(e), "e"); } };
  return <DrawerFrame onClose={closeDrawer} head={<><span className="rid" style={{ fontSize: 14.5 }}>{c.name}</span><Pill s={c.blockReason ? "Blocked" : "Active"} /></>}
    actions={<>{can("cust.price") && <button className="b b-o b-s" onClick={() => openModal(<OverrideModal c={c} />)}>Price overrides</button>}{can("payment.create") && <button className="b b-o b-s" onClick={() => openModal(<PaymentModal customerId={id} />)}>Record payment</button>}{can("cust.block") && (c.blockReason ? <button className="b b-o b-s" onClick={unblock}>Lift block</button> : <button className="b b-d b-s" onClick={() => openModal(<BlockModal c={c} />, "n")}>Temporary block</button>)}</>}>
    <Section t="Firm"><DF k="Contact" v={c.contactName} /><DF k="Phone" v={c.phone} /><DF k="Tehsil / district" v={c.tehsil + ", Rajasthan"} /><DF k="Address" v={`${c.address}, ${c.tehsil}`} /><DF k="GSTIN" v={c.gstin ?? "—"} mono /><DF k="Firm type" v={c.firmType} /><DF k="Pricing group" v={`${c.group} · ×${c.multiplier}`} /><DF k="Refer code" v={c.referCode} mono /><DF k="Sales executive" v={c.salesExec?.name ?? "—"} /><DF k="Deals in" v={c.linesEnabled.map((l) => lines?.find((x) => x.id === l)?.name ?? l).join(", ")} /></Section>
    {c.blockReason && <Note k="w"><b>Blocked</b> by {c.blockedBy} on {fDate(c.blockedAt)} — {c.blockReason}{c.blockUntil ? ` · auto-lift ${fDate(c.blockUntil)}` : ""}</Note>}
    <Section t="Contacts & logins">{c.contacts.map((ct) => <DF key={ct.id} k={<>{ct.name} <span className="sm">{ct.role}</span></>} v={<>{ct.phone} {ct.hasLogin && <span className="bd b-ok" style={{ marginLeft: 4 }}>login</span>}</>} mono />)}<div className="sm" style={{ marginTop: 6 }}>Owner authority may approve a credit-breaching order; Staff cannot — it routes to the owner.</div></Section>
    <Section t="Credit gate · time or amount, whichever first"><DF k="Credit limit" v={money(c.creditLimit)} mono /><DF k="Outstanding" v={<span style={{ color: g.amountBreach ? "var(--er)" : undefined }}>{money(g.out)}</span>} mono /><DF k="Credit days" v={c.creditDays || "Advance"} mono /><DF k="Oldest unpaid" v={<span style={{ color: g.timeBreach ? "var(--er)" : undefined }}>{g.oldestAge ? g.oldestAge + " days" : "—"}</span>} mono /><DF k="Gate mode" v={c.gateMode} /><div style={{ marginTop: 8 }}><Bar pct={g.util * 100} color={g.restricted ? "var(--er)" : g.util > .85 ? "var(--wa)" : "var(--ok)"} /></div><div className="sm" style={{ marginTop: 5 }}>{Math.round(g.util * 100)}% of limit used{g.restricted ? ` — ${g.amountBreach ? "amount breached" : ""}${g.amountBreach && g.timeBreach ? " and " : ""}${g.timeBreach ? "credit days exceeded" : ""}` : ""}</div></Section>
    <Section t="Machines owned">{c.machines.length ? c.machines.map((m) => <div key={m.id} style={{ border: "1px solid var(--bd)", borderRadius: 5, padding: "8px 10px", marginBottom: 6 }}><div style={{ fontSize: 13.5, fontWeight: 700, marginBottom: 4 }}>{m.type}</div>{Object.keys(m.spec).map((k) => <div className="df" key={k} style={{ fontSize: 13 }}><span className="k">{SPEC[k] ?? k}</span><span className="v">{m.spec[k]}</span></div>)}</div>) : <div className="sm">No machines recorded. This firm buys finished goods only.</div>}<div className="sm">Machine profile drives consumables reorder prediction and targeted ad slots.</div></Section>
    <Section t="Ageing">{a.labels.map((l, i) => <DF key={l} k={l} v={<span style={{ color: i >= 3 && a.buckets[i] ? "var(--er)" : undefined }}>{money(a.buckets[i])}</span>} mono />)}</Section>
    <Section t="Recent ledger">{c.statement.slice(-6).reverse().map((e) => <DF key={e.id} k={<span style={{ fontSize: 13 }}>{fDate(e.date)} · {e.particular}</span>} v={<span style={{ color: e.credit ? "var(--ok)" : undefined }}>{e.credit ? "−" + money(e.credit) : money(e.debit)}</span>} mono />)}</Section>
    <Section t={`Orders · ${c.orders.length}`}><Timeline rows={c.orders.slice(0, 6).map((o) => ({ t: <><span className="wo">{o.id}</span> {money(o.total)} · {o.status.replace(/_/g, " ")}</>, n: fDT(o.createdAt) }))} /></Section>
  </DrawerFrame>;
}

function BlockModal({ c }: { c: Customer }) {
  const { closeModal, closeDrawer, toast } = useUI(); const [r, setR] = useState(""); const [d, setD] = useState("");
  const go = async () => { if (!r.trim()) return toast("A reason is required", "e"); try { await post(`/api/customers/${c.id}/block`, { reason: r, until: d || undefined }); toast("Block applied — ordering suspended, ledger stays open", "s"); closeModal(); closeDrawer(); refresh("/api/"); } catch (e) { toast(errMsg(e), "e"); } };
  return <ModalFrame title={"Temporary block — " + c.name} onClose={closeModal} actions={<><button className="b b-o" onClick={closeModal}>Cancel</button><button className="b b-d" onClick={go}>Apply block</button></>}><Note k="w" style={{ marginBottom: 13 }}>A block suspends <b>new orders only</b>. Ledger, statements and payment stay open so the firm can clear dues and be unblocked — BR-05.</Note><Field label="Reason (required)"><textarea value={r} onChange={(e) => setR(e.target.value)} placeholder="e.g. Two cheques returned, awaiting clearance" /></Field><Field label="Auto-lift on (optional)"><input type="date" value={d} onChange={(e) => setD(e.target.value)} /></Field></ModalFrame>;
}

function OverrideModal({ c }: { c: Full }) {
  const { closeModal, toast } = useUI(); const { data: items } = useApi<{ items: ItemView[] }>("/api/items"); const { data: full, mutate } = useApi<Full>(`/api/customers/${c.id}`);
  const its = (items?.items ?? []).filter((i) => i.status === "ACTIVE" && c.linesEnabled.includes(i.lineId));
  const [iid, setIid] = useState(""); const [rate, setRate] = useState(55);
  const list = full?.overrides ?? c.overrides;
  const add = async () => { try { const r = await put<{ belowFloor: boolean; floor: number }>(`/api/customers/${c.id}/overrides/${iid || its[0]?.id}`, { rate: Number(rate) }); toast(r.belowFloor ? `Set at ${money(rate)} — below floor ${money(r.floor)}, logged in audit` : "Override set", r.belowFloor ? "w" : "s"); mutate(); refresh("/api/customers"); } catch (e) { toast(errMsg(e), "e"); } };
  const rm = async (itemId: string) => { await del(`/api/customers/${c.id}/overrides/${itemId}`); toast("Override removed", "s"); mutate(); refresh("/api/customers"); };
  return <ModalFrame title={"Price overrides — " + c.name} onClose={closeModal} actions={<><button className="b b-o" onClick={closeModal}>Close</button><button className="b b-p" onClick={add}>Set override</button></>}>
    <Note style={{ marginBottom: 13 }}>An override outranks the quantity slab and the group multiplier. It still cannot go below the margin floor without an authorised override.</Note>
    {list.length ? <table className="dg" style={{ marginBottom: 13 }}><thead><tr><th>Item</th><th className="n">Slab rate</th><th className="n">Group rate</th><th className="n">Override</th><th></th></tr></thead><tbody>{list.map((o) => <tr key={o.itemId} style={{ cursor: "default" }}><td>{o.sku} {o.name}</td><td className="n tab">{money(o.slabRate)}</td><td className="n tab">{money(o.groupRate)}</td><td className="n tab" style={{ fontWeight: 700, color: o.rate < o.floor ? "var(--er)" : "var(--ac)" }}>{money(o.rate)}</td><td><button className="b b-g b-s" onClick={() => rm(o.itemId)}>Remove</button></td></tr>)}</tbody></table> : <div className="sm" style={{ marginBottom: 13 }}>No overrides set for this firm.</div>}
    <div className="fg"><Field label="Item"><select value={iid || its[0]?.id || ""} onChange={(e) => setIid(e.target.value)}>{its.map((i) => <option key={i.id} value={i.id}>{i.sku} — {i.name}</option>)}</select></Field><Field label="Override rate (₹ per unit)"><input type="number" value={rate} onChange={(e) => setRate(Number(e.target.value))} /></Field></div>
  </ModalFrame>;
}

export function PaymentModal({ customerId }: { customerId?: string }) {
  const { closeModal, closeDrawer, toast } = useUI(); const { data: custs } = useApi<Customer[]>("/api/customers");
  const [f, setF] = useState(() => ({ customerId: customerId ?? "", amount: 25000, method: "UPI", ref: "REF" + (880900 + Math.floor(Math.random() * 900)), date: new Date().toISOString().slice(0, 10) }));
  const go = async () => { try { const r = await post<{ receiptNo: string; outstanding: number; autoLifted: boolean }>("/api/ledger/payments", { ...f, customerId: f.customerId || custs?.[0]?.id, amount: Number(f.amount) }); toast(`Receipt ${r.receiptNo} posted · outstanding now ${money(r.outstanding)}${r.autoLifted ? " · block auto-lifted" : ""}`, "s"); closeModal(); closeDrawer(); refresh("/api/"); } catch (e) { toast(errMsg(e), "e"); } };
  return <ModalFrame title="Record payment" onClose={closeModal} actions={<><button className="b b-o" onClick={closeModal}>Cancel</button><button className="b b-p" onClick={go}>Post receipt</button></>}>
    <div className="fg"><Field label="Firm" full><select value={f.customerId || custs?.[0]?.id || ""} onChange={(e) => setF({ ...f, customerId: e.target.value })}>{custs?.map((c) => <option key={c.id} value={c.id}>{c.name} — outstanding {money(c.gate.out)}</option>)}</select></Field><Field label="Amount (₹)"><input type="number" value={f.amount} onChange={(e) => setF({ ...f, amount: Number(e.target.value) })} /></Field><Field label="Method"><select value={f.method} onChange={(e) => setF({ ...f, method: e.target.value })}><option>UPI</option><option>NEFT</option><option>Cheque</option><option>Cash</option></select></Field><Field label="Reference"><input value={f.ref} onChange={(e) => setF({ ...f, ref: e.target.value })} /></Field><Field label="Date"><input type="date" value={f.date} onChange={(e) => setF({ ...f, date: e.target.value })} /></Field></div>
    <Note style={{ marginTop: 11 }}>Receipts allocate oldest-invoice-first by default. Any unallocated amount sits as on-account credit.</Note>
  </ModalFrame>;
}

export function CustomerForm() {
  const { closeModal, toast } = useUI(); const { data: lines } = useLines(); const { data: tehsils } = useApi<string[]>("/api/masters/tehsils"); const { data: execs } = useApi<{ id: string; name: string }[]>("/api/masters/sales-execs"); const { data: groups } = useApi<{ name: string; multiplier: number }[]>("/api/masters/pricing-groups");
  const [f, setF] = useState({ name: "", contactName: "", phone: "", tehsil: "Bikaner", gstin: "", firmType: "Registered", linesEnabled: ["L1"], group: "Regular", salesExecId: "", creditLimit: 150000, creditDays: 30, gateMode: "WARN" });
  const go = async () => { if (!f.name || !f.contactName || !f.phone) return toast("Firm name, owner name and phone are required", "e"); try { await post("/api/customers", { ...f, salesExecId: f.salesExecId || null, gstin: f.gstin || undefined }); toast("Customer created — refer code issued", "s"); closeModal(); refresh("/api/customers"); } catch (e) { toast(errMsg(e), "e"); } };
  return <ModalFrame title="New customer" onClose={closeModal} actions={<><button className="b b-o" onClick={closeModal}>Cancel</button><button className="b b-p" onClick={go}>Save customer</button></>}>
    <div className="fg"><Field label="Firm name *"><input value={f.name} onChange={(e) => setF({ ...f, name: e.target.value })} placeholder="e.g. Marwar Card Bhandar" /></Field><Field label="Owner name *"><input value={f.contactName} onChange={(e) => setF({ ...f, contactName: e.target.value })} /></Field><Field label="Phone *"><input value={f.phone} onChange={(e) => setF({ ...f, phone: e.target.value })} placeholder="+91 94141 00000" /></Field><Field label="Tehsil / gram panchayat *"><select value={f.tehsil} onChange={(e) => setF({ ...f, tehsil: e.target.value })}>{tehsils?.map((t) => <option key={t}>{t}</option>)}</select></Field><Field label="GSTIN"><input value={f.gstin} onChange={(e) => setF({ ...f, gstin: e.target.value })} placeholder="08ABCDE1234F1Z5" /></Field><Field label="Firm type"><select value={f.firmType} onChange={(e) => setF({ ...f, firmType: e.target.value })}><option>Registered</option><option>Composition</option><option>Unregistered</option></select></Field>
      <Field label="Deals in (drives which lines they see in the portal)" full><div style={{ display: "flex", gap: 12, flexWrap: "wrap", padding: "7px 0" }}>{lines?.map((l) => <label key={l.id} style={{ display: "flex", gap: 6, alignItems: "center", fontSize: 14 }}><input type="checkbox" className="ck" checked={f.linesEnabled.includes(l.id)} onChange={(e) => setF({ ...f, linesEnabled: e.target.checked ? [...f.linesEnabled, l.id] : f.linesEnabled.filter((x) => x !== l.id) })} />{l.name}</label>)}</div></Field>
      <Field label="Pricing group"><select value={f.group} onChange={(e) => setF({ ...f, group: e.target.value })}>{groups?.map((g) => <option key={g.name} value={g.name}>{g.name} — ×{g.multiplier}</option>)}</select></Field><Field label="Sales executive"><select value={f.salesExecId} onChange={(e) => setF({ ...f, salesExecId: e.target.value })}><option value="">—</option>{execs?.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select></Field>
      <Field label="Credit limit (₹)" hint="Suggested ₹1,80,000 from machine capacity"><input type="number" value={f.creditLimit} onChange={(e) => setF({ ...f, creditLimit: Number(e.target.value) })} /></Field><Field label="Credit days" hint="Time or amount, whichever breaches first"><input type="number" value={f.creditDays} onChange={(e) => setF({ ...f, creditDays: Number(e.target.value) })} /></Field>
      <Field label="Gate mode" full><select value={f.gateMode} onChange={(e) => setF({ ...f, gateMode: e.target.value })}><option value="WARN">WARN — allow with a recorded reason</option><option value="BLOCK">BLOCK — needs an authorised override</option></select></Field></div>
    <Note style={{ marginTop: 11 }}>Mandatory minimum is firm name, one contact with a phone, and tehsil. Everything else can follow — a half-captured customer is worth more than an abandoned form.</Note>
  </ModalFrame>;
}
export { money2 };
