"use client";
import { useState } from "react";
import { fDate } from "@vivaha/shared";
import { useApi } from "@/lib/hooks";
import { useUI } from "@/lib/ui";
import { post } from "@/lib/api";
import { usePortal } from "@/components/portal/PortalContext";
import { Sect } from "@/components/portal/Bits";
import { thumb } from "@/lib/art";

type Lite = { id: string; sku: string; designNo: string | null; name: string; artSeed: number; lineId: string; imageUrl: string | null };
interface KitState { version: string; versionName: string; isLatest: boolean; issuedAt: string; lastScanAt: string | null; expectedCount: number; session: { scanned: number; offline: boolean; pending: number; lastItem: Lite | null } | null; buckets: { matched: Lite[]; missing: Lite[]; retired: Lite[]; unlisted: Lite[] } | null }
const B = [["matched", "✓", "मिले", "var(--ok)"], ["missing", "⚠", "नहीं मिले", "var(--wa)"], ["retired", "✕", "हटाएं", "var(--er)"], ["unlisted", "◆", "सूची में नहीं", "var(--ac)"]] as const;
export default function KitPage() {
  const { data: k, mutate } = useApi<KitState>("/api/portal/kit"); const { toast } = useUI(); const P = usePortal(); const [sel, setSel] = useState<string | null>(null);
  const act = async (p: string, msg?: string) => { try { const r = await post<{ added?: number } | KitState>(`/api/portal/kit/${p}`, p === "scan" ? { offline: Math.random() < .18 } : {}); mutate(); if (msg) toast(msg, "s"); if (p === "finish") { const a = (r as { added?: number }).added ?? 0; toast(`जाँच पूरी — ${a} आइटम कार्ट में जोड़े गए`, "s"); P.reload(); if (a) setTimeout(P.openCart, 700); } } catch (e) { toast(e instanceof Error ? e.message : "Error", "w"); } };
  if (!k) return null; const s = k.session; const bk = (k.buckets ?? {}) as unknown as Record<string, Lite[]>;
  const lbl: Record<string, string> = { matched: "मिले", missing: "नहीं मिले — ऑर्डर में जुड़ेंगे", retired: "हटाएं — अब नहीं बनते", unlisted: "सूची में नहीं — किसी और से लिए गए" };
  return <><Sect t="किट सुधार" />
    {!s ? <><div className="kitp"><div style={{ fontSize: 14, fontWeight: 700 }} className="hi">आपकी किट — {k.version}</div><div className="sm hi" style={{ marginTop: 4 }}>{k.expectedCount} कार्ड · {fDate(k.issuedAt)} को दी गई{k.lastScanAt ? ` · आख़िरी जाँच ${fDate(k.lastScanAt)}` : " · अभी तक जाँच नहीं हुई"}</div>{!k.isLatest && <div className="note w hi" style={{ marginTop: 10 }}>आपकी किट पिछले सीज़न की है। नए डिज़ाइन इसमें नहीं हैं — जाँच के बाद अपने आप ऑर्डर बन जाएगा।</div>}<button className="b b-p hi" style={{ width: "100%", height: 46, marginTop: 12, fontSize: 15 }} onClick={() => act("start", "स्कैन सत्र शुरू — बीच में रोक सकते हैं")}>स्कैन शुरू करें</button><div className="sm hi" style={{ marginTop: 9, textAlign: "center" }}>एक-एक करके कार्ड स्कैन कीजिए · बीच में रोक सकते हैं · इंटरनेट जाए तो भी चलेगा</div></div>
      <div className="blk"><div className="lb">जाँच के बाद क्या मिलेगा</div>{[["✓", "मिले — जो किट में हैं और स्कैन हुए", "var(--ok)"], ["⚠", "नहीं मिले — किट में हैं पर स्कैन नहीं हुए, ऑर्डर में जुड़ जाएंगे", "var(--wa)"], ["✕", "हटाएं — स्कैन हुए पर अब बनते नहीं", "var(--er)"], ["◆", "सूची में नहीं — स्कैन हुए पर किसी किट में नहीं", "var(--ac)"]].map((r) => <div key={r[0]} style={{ display: "flex", gap: 9, padding: "6px 0", fontSize: 12.5 }}><span style={{ color: r[2], fontWeight: 700 }}>{r[0]}</span><span className="hi">{r[1]}</span></div>)}</div></>
    : <><div className="kitp"><div style={{ display: "flex", alignItems: "center", gap: 9 }}><b className="hi" style={{ fontSize: 13.5 }}>{k.version}</b><span className="sm tab" style={{ marginLeft: "auto" }}>{s.scanned} / {k.expectedCount}</span></div><div className="kprog"><i style={{ width: Math.round((s.scanned / Math.max(1, k.expectedCount)) * 100) + "%" }} /></div>{s.offline && <div className="note w hi" style={{ marginTop: 8 }}>इंटरनेट नहीं है — {s.pending} स्कैन सेव हो रहे हैं, बाद में अपने आप भेज दिए जाएंगे</div>}<button className="b b-p hi" style={{ width: "100%", height: 52, marginTop: 11, fontSize: 15 }} onClick={() => act("scan")}>📷 अगला कार्ड स्कैन करें</button>{s.lastItem && <div className="sm hi" style={{ marginTop: 8, textAlign: "center" }}>आख़िरी: {s.lastItem.name} ✓</div>}</div>
      {B.map(([key, ic, l, col]) => <div key={key} onClick={() => setSel(sel === key ? null : key)} className="kbuck" style={key === "unlisted" ? { borderColor: "var(--ac-bd)", background: "var(--ac-bg)" } : undefined}><span style={{ color: col, fontWeight: 700 }}>{ic}</span><span className="hi">{l}</span><span className="n2" style={{ color: col }}>{bk[key].length}</span></div>)}
      <div style={{ display: "flex", gap: 9, marginTop: 12 }}><button className="b b-o hi" style={{ flex: 1, height: 42 }} onClick={() => { act("pause", "रोक दिया — जहाँ छोड़ा वहीं से शुरू होगा"); setSel(null); }}>रोकें, बाद में करें</button><button className="b b-p hi" style={{ flex: 1, height: 42 }} onClick={() => act("finish")}>ख़त्म करें व ऑर्डर बनाएं</button></div>
      {sel && <div className="blk" style={{ marginTop: 12 }}><div className="lb">{lbl[sel]} · {bk[sel].length}</div>{bk[sel].length ? bk[sel].slice(0, 40).map((it) => <div key={it.id} style={{ display: "flex", gap: 9, alignItems: "center", padding: "7px 0", borderBottom: "1px solid var(--bd-soft)" }}><img className="cw" src={thumb(it, 40, 52)} alt="" style={{ width: 32, border: "1px solid var(--bd)", borderRadius: 3 }} /><div style={{ flex: 1, minWidth: 0 }}><div style={{ fontSize: 12, fontWeight: 600 }}>{it.name}</div><div className="sm">{it.designNo || it.sku}</div></div>{sel === "retired" ? <span className="bd b-er hi">हटाएं</span> : sel === "missing" ? <span className="bd b-wa hi">मंगाएं</span> : null}</div>) : <div className="sm hi">कुछ नहीं</div>}</div>}</>}
  </>;
}
