"use client";
import { useState } from "react";
import { num, fDate } from "@vivaha/shared";
import { useApi } from "@/lib/hooks";
import { useUI } from "@/lib/ui";
import { post } from "@/lib/api";
import { Sect } from "@/components/portal/Bits";
export default function ReferPage() {
  const { data, mutate } = useApi<{ code: string; rows: { id: string; name: string; tehsil: string; state: string; reward: number; createdAt: string }[] }>("/api/portal/referrals"); const { data: tehsils } = useApi<string[]>("/api/portal/tehsils"); const { toast } = useUI();
  const [f, setF] = useState({ name: "", address: "", tehsil: "Bikaner", phone: "" });
  const go = async () => { if (!f.name || !f.phone) return toast("नाम और नंबर ज़रूरी है", "e"); try { await post("/api/portal/referrals", f); toast("भेज दिया — हमारा आदमी संपर्क करेगा", "s"); setF({ name: "", address: "", tehsil: "Bikaner", phone: "" }); mutate(); } catch (e) { toast(e instanceof Error ? e.message : "Error", "e"); } };
  const ST: Record<string, [string, string, string]> = { "Reward released": ["✓", "var(--ok)", "जमा"], "First order pending": ["●", "var(--wa)", "पहला ऑर्डर बाकी"], Contacted: ["○", "var(--t4)", "संपर्क किया"], Submitted: ["○", "var(--t4)", "भेजा गया"] };
  return <><Sect t="रेफ़र करें और कमाएं" /><div className="blk" style={{ textAlign: "center" }}><div className="lb">आपका कोड</div><div className="tab" style={{ fontSize: 24, fontWeight: 700, letterSpacing: ".04em", color: "var(--ac)", margin: "6px 0 12px" }}>{data?.code}</div><div style={{ display: "flex", gap: 8 }}><button className="b b-o hi" style={{ flex: 1 }} onClick={() => { navigator.clipboard?.writeText(data?.code ?? ""); toast("कोड कॉपी हो गया", "s"); }}>कॉपी करें</button><button className="b b-p hi" style={{ flex: 1 }} onClick={() => toast("WhatsApp खुल रहा है", "i")}>WhatsApp पर भेजें</button></div><div className="note o hi" style={{ marginTop: 11, textAlign: "left" }}>हर नए ग्राहक के <b>पहले भुगतान</b> पर ₹2,000 आपके खाते में जमा। सिर्फ़ नाम लिखवाने पर नहीं।</div></div>
    <div className="blk"><div className="lb">या पूरी जानकारी भेजें</div><input className="scani hi" value={f.name} onChange={(e) => setF({ ...f, name: e.target.value })} placeholder="पार्टी का नाम" style={{ marginTop: 0 }} /><input className="scani hi" value={f.address} onChange={(e) => setF({ ...f, address: e.target.value })} placeholder="पता" /><select className="scani hi" value={f.tehsil} onChange={(e) => setF({ ...f, tehsil: e.target.value })}>{tehsils?.map((t) => <option key={t}>{t}</option>)}</select><input className="scani hi" value={f.phone} onChange={(e) => setF({ ...f, phone: e.target.value })} placeholder="संपर्क नंबर" /><button className="b b-p hi" style={{ width: "100%", marginTop: 10 }} onClick={go}>भेजें</button></div>
    <Sect t="आपके रेफ़रल" more={String(data?.rows.length ?? 0)} /><div className="blk">{data?.rows.length ? data.rows.map((r) => { const s = ST[r.state] ?? ST.Submitted; return <div key={r.id} style={{ display: "flex", gap: 10, alignItems: "center", padding: "9px 0", borderBottom: "1px solid var(--bd-soft)" }}><span style={{ color: s[1], fontSize: 15.5 }}>{s[0]}</span><div style={{ flex: 1, minWidth: 0 }}><div style={{ fontSize: 14, fontWeight: 600 }}>{r.name}</div><div className="sm">{r.tehsil} · {fDate(r.createdAt)}</div></div><span className="hi" style={{ fontSize: 13, color: s[1], fontWeight: 600 }}>{r.state === "Reward released" ? "₹" + num(r.reward) + " " : ""}{s[2]}</span></div>; }) : <div className="sm hi">अभी कोई रेफ़रल नहीं</div>}</div></>;
}
