"use client";
import { useState } from "react";
import { money, money2, num, fDate, AGEING_LABELS, type CreditGate } from "@vivaha/shared";
import { useApi } from "@/lib/hooks";
import { useAuth } from "@/lib/auth-context";
import { useUI } from "@/lib/ui";
import { PageHead } from "@/components/PageHead";
import { useFooter, usePager } from "@/components/Shell";
import { KPI, DF, Section, DrawerFrame, Note, Panel } from "@/components/ui";
import { PaymentModal } from "@/components/CustomerDrawer";
import { InvoiceModal } from "@/components/InvoiceModal";
import { exportCsv } from "@/lib/csv";
import { Icon } from "@/components/icons";

const HSN_DESC: Record<string, string> = { "4817": "Envelopes, letter cards, printed stationery", "3215": "Printing ink", "3814": "Organic composite solvents", "5911": "Textile products for technical use", "3701": "Photographic plates", "3707": "Chemical preparations for photographic use", "3921": "Plastic sheets, film, foil", "7606": "Aluminium plates, sheets", "3920": "Acrylic sheets", "5603": "Non-wovens", "9989": "Other manufacturing services" };
interface OutRow { id: string; name: string; tehsil: string; creditDays: number; gateMode: string; creditLimit: number; gate: CreditGate; ageing: number[] }
interface Inv { no: string; date: string; orderId: string; taxable: number; cgst: number; sgst: number; igst: number; total: number; customer: { name: string; gstin: string | null } }
interface Pay { id: string; date: string; method: string; ref: string; amount: number; by: string; customerId: string; customer: { name: string } }

export default function AccountsPage() {
  const { can } = useAuth(); const { openDrawer, openModal } = useUI(); const [tab, setTab] = useState("out");
  const { data: out } = useApi<{ rows: OutRow[]; total: number; buckets: number[] }>("/api/ledger/outstanding"); const { data: invs } = useApi<Inv[]>("/api/ledger/invoices"); const { data: pays } = useApi<Pay[]>("/api/ledger/payments"); const { data: gst } = useApi<{ invoices: number; taxable: number; tax: number; b2b: number; b2c: number; hsn: { hsn: string; gstPct: number; qty: number; taxable: number; tax: number }[] }>("/api/ledger/gst-summary");
  const list = tab === "out" ? out?.rows ?? [] : tab === "inv" ? invs ?? [] : tab === "pay" ? pays ?? [] : gst?.hsn ?? [];
  const pg = usePager(list as unknown[]); useFooter(list.length, "", pg.page, pg.pages, pg.setPage);
  const gstr1 = () => exportCsv("gstr1", ["Invoice", "Date", "Firm", "GSTIN", "Taxable", "CGST", "SGST", "IGST", "Total"], (invs ?? []).map((i) => [i.no, fDate(i.date), i.customer.name, i.customer.gstin, i.taxable.toFixed(2), i.cgst.toFixed(2), i.sgst.toFixed(2), i.igst.toFixed(2), i.total.toFixed(2)]));
  return <>
    <PageHead crumb={["Finance", "Ledger & GST"]} title="Ledger & GST" sub="The ledger is the only source of truth for outstanding — no screen stores or edits a balance" actions={<><button className="b b-o" onClick={gstr1}><Icon n="download" s={13} /> GSTR-1 data</button>{can("payment.create") && <button className="b b-p" onClick={() => openModal(<PaymentModal />)}>+ Record payment</button>}</>} tabs={[{ k: "out", l: "Outstanding", n: out?.rows.length }, { k: "inv", l: "Invoice register", n: invs?.length }, { k: "pay", l: "Receipts", n: pays?.length }, { k: "gst", l: "GST summary" }]} tab={tab} onTab={setTab} />
    <div className="wa">
      {tab === "out" && out && <><div className="kpis c5"><KPI l="Total receivable" v={money(out.total)} />{AGEING_LABELS.slice(1).map((l, i) => <KPI key={l} l={l + " days"} v={<span style={{ color: i >= 2 ? "var(--er)" : undefined }}>{money(out.buckets[i + 1])}</span>} d={Math.round((out.buckets[i + 1] / Math.max(1, out.total)) * 100) + "% of book"} />)}</div>
        <div className="gw"><table className="dg"><thead><tr><th>Firm</th><th>Terms</th><th className="n">Limit</th><th className="n">Outstanding</th><th className="n">Available</th>{AGEING_LABELS.map((l) => <th className="n" key={l}>{l}</th>)}<th>Gate</th><th></th></tr></thead><tbody>
          {(pg.rows as OutRow[]).map((r) => <tr key={r.id} onClick={() => openDrawer(<LedgerDrawer id={r.id} />)}><td className="w"><span className="rid">{r.name}</span><div className="sm">{r.tehsil}</div></td><td className="sm">{r.creditDays ? "Net " + r.creditDays : "Advance"} · {r.gateMode}</td><td className="n tab">{money(r.creditLimit)}</td><td className="n tab" style={{ fontWeight: 700, color: "var(--t9)" }}>{money(r.gate.out)}</td><td className="n tab" style={{ color: r.creditLimit - r.gate.out < 0 ? "var(--er)" : "var(--ok)" }}>{money(r.creditLimit - r.gate.out)}</td>{r.ageing.map((b, i) => <td key={i} className="n tab" style={{ color: i >= 3 && b ? "var(--er)" : b ? "var(--t6)" : "var(--t4)" }}>{b ? money(b) : "—"}</td>)}<td>{r.gate.restricted ? <span className="bd b-er">{r.gate.amountBreach ? "Amount" : ""}{r.gate.amountBreach && r.gate.timeBreach ? " + " : ""}{r.gate.timeBreach ? "Time" : ""}</span> : <span className="bd b-ok">OK</span>}</td><td>{can("payment.create") && <button className="b b-o b-s" onClick={(e) => { e.stopPropagation(); openModal(<PaymentModal customerId={r.id} />); }}>Receipt</button>}</td></tr>)}
        </tbody></table></div></>}
      {tab === "inv" && <><div className="gw"><table className="dg"><thead><tr><th>Invoice</th><th>Date</th><th>Firm</th><th>GSTIN</th><th>Order</th><th className="n">Taxable</th><th className="n">CGST</th><th className="n">SGST</th><th className="n">IGST</th><th className="n">Total</th></tr></thead><tbody>{(pg.rows as Inv[]).map((i) => <tr key={i.no} onClick={() => openModal(<InvoiceModal no={i.no} orderId={i.orderId} />, "w")}><td><span className="rid">{i.no}</span></td><td className="tab">{fDate(i.date)}</td><td className="w">{i.customer.name}</td><td className="sm">{i.customer.gstin}</td><td className="sm">{i.orderId}</td><td className="n tab">{money2(i.taxable)}</td><td className="n tab">{i.cgst ? money2(i.cgst) : "—"}</td><td className="n tab">{i.sgst ? money2(i.sgst) : "—"}</td><td className="n tab">{i.igst ? money2(i.igst) : "—"}</td><td className="n tab" style={{ fontWeight: 700, color: "var(--t9)" }}>{money2(i.total)}</td></tr>)}</tbody></table></div><Note k="i" style={{ marginTop: 11 }}>Numbering is sequential and gapless per financial year per series. A cancelled invoice keeps its number and is marked cancelled — never reused.</Note></>}
      {tab === "pay" && <div className="gw"><table className="dg"><thead><tr><th>Receipt</th><th>Date</th><th>Firm</th><th>Method</th><th>Reference</th><th className="n">Amount</th><th>Recorded by</th></tr></thead><tbody>{(pg.rows as Pay[]).map((p) => <tr key={p.id} onClick={() => openDrawer(<LedgerDrawer id={p.customerId} />)}><td><span className="rid">{p.id}</span></td><td className="tab">{fDate(p.date)}</td><td className="w">{p.customer.name}</td><td>{p.method}</td><td className="sm">{p.ref}</td><td className="n tab" style={{ fontWeight: 700, color: "var(--ok)" }}>{money(p.amount)}</td><td className="sm">{p.by}</td></tr>)}</tbody></table></div>}
      {tab === "gst" && gst && <><div className="kpis"><KPI l="Invoices" v={gst.invoices} /><KPI l="Taxable value" v={money(gst.taxable)} /><KPI l="Output tax" v={money(gst.tax)} /><KPI l="B2B / B2C" v={<span style={{ fontSize: 16 }}>{gst.b2b} / {gst.b2c}</span>} /></div>
        <Panel t="HSN-wise summary" h="the shape GSTR-1 needs"><div className="gw" style={{ border: "none", borderRadius: 0 }}><table className="dg"><thead><tr><th>HSN</th><th>Description</th><th className="n">Rate</th><th className="n">Quantity</th><th className="n">Taxable value</th><th className="n">Tax</th></tr></thead><tbody>{gst.hsn.map((r) => <tr key={r.hsn + r.gstPct} style={{ cursor: "default" }}><td className="rid">{r.hsn}</td><td>{HSN_DESC[r.hsn] ?? "—"}</td><td className="n tab">{r.gstPct}%</td><td className="n tab">{num(r.qty)}</td><td className="n tab">{money2(r.taxable)}</td><td className="n tab" style={{ fontWeight: 600, color: "var(--t9)" }}>{money2(r.tax)}</td></tr>)}</tbody></table></div></Panel></>}
    </div>
  </>;
}
export function LedgerDrawer({ id }: { id: string }) {
  const { data } = useApi<{ customer: { name: string; creditLimit: number }; gate: CreditGate; ageing: { buckets: number[]; labels: string[] }; statement: { id: string; date: string; particular: string; debit: number; credit: number; bal: number }[] }>(`/api/ledger/customers/${id}`); const { closeDrawer, openModal, toast } = useUI(); const { can } = useAuth();
  if (!data) return <div className="drb">Loading…</div>; const { customer: c, gate: g, ageing: a } = data;
  return <DrawerFrame onClose={closeDrawer} head={<><span className="rid" style={{ fontSize: 13 }}>{c.name}</span><span className="bd b-nu">Ledger</span></>} actions={<>{can("payment.create") && <button className="b b-p b-s" onClick={() => openModal(<PaymentModal customerId={id} />)}>Record payment</button>}<button className="b b-o b-s" onClick={() => toast("Statement sent on WhatsApp", "s")}>Send statement</button></>}>
    <Section t="Position"><DF k="Outstanding (derived from ledger)" v={<span style={{ fontWeight: 700, color: g.restricted ? "var(--er)" : undefined }}>{money(g.out)}</span>} mono /><DF k="Credit limit" v={money(c.creditLimit)} mono /><DF k="Available credit" v={money(c.creditLimit - g.out)} mono /><DF k="Oldest unpaid" v={<span style={{ color: g.timeBreach ? "var(--er)" : undefined }}>{g.oldestAge ? `${g.oldestAge} days · ${g.oldestRef ?? ""}` : "nothing overdue"}</span>} mono /></Section>
    <Section t="Ageing">{a.labels.map((l, i) => <DF key={l} k={l} v={money(a.buckets[i])} mono />)}</Section>
    <Section t="Statement"><table className="dg" style={{ fontSize: 11.5 }}><thead><tr><th>Date</th><th>Particular</th><th className="n">Debit</th><th className="n">Credit</th><th className="n">Balance</th></tr></thead><tbody>{data.statement.slice().reverse().map((e) => <tr key={e.id} style={{ cursor: "default" }}><td className="tab">{fDate(e.date)}</td><td className="w" style={{ whiteSpace: "normal" }}>{e.particular}</td><td className="n tab">{e.debit ? money2(e.debit) : "—"}</td><td className="n tab" style={{ color: "var(--ok)" }}>{e.credit ? money2(e.credit) : "—"}</td><td className="n tab" style={{ fontWeight: 700, color: "var(--t9)" }}>{money2(e.bal)}</td></tr>)}</tbody></table></Section>
  </DrawerFrame>;
}
