// Procedural product artwork (identical to the mock) — used until real images are uploaded.
const PALS = [["#7B1E3A", "#D4A03C", "#FBF3E4"], ["#1E3A6E", "#B9C4D6", "#F2F5FA"], ["#F0E2C8", "#B08838", "#FFFDF7"], ["#8C1B1B", "#E4C06A", "#FDF2E9"], ["#E9B7A0", "#C08552", "#FFF7F1"], ["#124E3C", "#C9A227", "#F1F8F3"], ["#B4557E", "#C8CDD4", "#FDF1F6"], ["#5E1B2E", "#B0763C", "#FAF0EC"], ["#8A6A1E", "#7B1E2B", "#FBF6E6"], ["#F4EDE3", "#C08A4E", "#FFFDFA"], ["#2C2C54", "#C6A15B", "#F3F2F8"], ["#0F5E63", "#D8B54A", "#EEF7F7"]];
function artSVG(seed: number, w: number, h: number) {
  const p = PALS[seed % PALS.length], m = seed % 5; let inner = "";
  if (m === 0) inner = `<rect x="9" y="9" width="${w - 18}" height="${h - 18}" fill="none" stroke="${p[1]}" stroke-width="1.6"/><rect x="14" y="14" width="${w - 28}" height="${h - 28}" fill="none" stroke="${p[1]}" stroke-width=".7" stroke-dasharray="3 2"/><circle cx="${w / 2}" cy="${h * .36}" r="${w * .13}" fill="none" stroke="${p[0]}" stroke-width="1.4"/><path d="M${w / 2 - w * .09} ${h * .36} Q${w / 2} ${h * .2} ${w / 2 + w * .09} ${h * .36} Q${w / 2} ${h * .52} ${w / 2 - w * .09} ${h * .36}Z" fill="${p[1]}" opacity=".55"/>`;
  else if (m === 1) inner = `<path d="M0 ${h * .3} Q${w * .5} ${h * .14} ${w} ${h * .3}" fill="none" stroke="${p[1]}" stroke-width="2"/><path d="M0 ${h * .72} Q${w * .5} ${h * .88} ${w} ${h * .72}" fill="none" stroke="${p[1]}" stroke-width="2"/><rect x="${w * .22}" y="${h * .38}" width="${w * .56}" height="${h * .26}" fill="none" stroke="${p[0]}" stroke-width="1.2"/><circle cx="${w * .5}" cy="${h * .51}" r="3.4" fill="${p[0]}"/>`;
  else if (m === 2) { let d = ""; for (let i = 0; i < 7; i++) { const a = i * Math.PI * 2 / 7, cx = w / 2 + Math.cos(a) * w * .14, cy = h * .42 + Math.sin(a) * w * .14; d += `<ellipse cx="${cx}" cy="${cy}" rx="${w * .055}" ry="${w * .028}" transform="rotate(${a * 180 / Math.PI} ${cx} ${cy})" fill="${p[1]}" opacity=".62"/>`; } inner = `<rect x="7" y="7" width="${w - 14}" height="${h - 14}" fill="none" stroke="${p[1]}" stroke-width="1"/>${d}<circle cx="${w / 2}" cy="${h * .42}" r="${w * .04}" fill="${p[0]}"/>`; }
  else if (m === 3) inner = `<rect x="0" y="0" width="${w}" height="${h * .17}" fill="${p[0]}" opacity=".82"/><rect x="0" y="${h * .83}" width="${w}" height="${h * .17}" fill="${p[0]}" opacity=".82"/><path d="M${w * .5} ${h * .3} L${w * .62} ${h * .5} L${w * .5} ${h * .7} L${w * .38} ${h * .5}Z" fill="none" stroke="${p[1]}" stroke-width="1.6"/><path d="M${w * .5} ${h * .37} L${w * .57} ${h * .5} L${w * .5} ${h * .63} L${w * .43} ${h * .5}Z" fill="${p[1]}" opacity=".5"/>`;
  else inner = `<rect x="11" y="11" width="${w - 22}" height="${h - 22}" fill="none" stroke="${p[0]}" stroke-width="1.3"/><line x1="11" y1="${h * .28}" x2="${w - 11}" y2="${h * .28}" stroke="${p[1]}" stroke-width="1"/><line x1="11" y1="${h * .72}" x2="${w - 11}" y2="${h * .72}" stroke="${p[1]}" stroke-width="1"/><text x="${w / 2}" y="${h * .56}" text-anchor="middle" font-size="${w * .2}" fill="${p[0]}" opacity=".78" font-family="serif">ॐ</text>`;
  return `data:image/svg+xml;utf8,` + encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}"><rect width="${w}" height="${h}" fill="${p[2]}"/>${inner}</svg>`);
}
function drumSVG(seed: number, w: number, h: number) {
  const c = ["#1D4E63", "#7A3B12", "#2C5E2E", "#5A2340", "#3D3A66"][seed % 5];
  return "data:image/svg+xml;utf8," + encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}"><rect width="${w}" height="${h}" fill="#F4F6F8"/><rect x="${w * .28}" y="${h * .2}" width="${w * .44}" height="${h * .62}" rx="4" fill="${c}"/><rect x="${w * .28}" y="${h * .34}" width="${w * .44}" height="${h * .16}" fill="#fff" opacity=".85"/><ellipse cx="${w * .5}" cy="${h * .2}" rx="${w * .22}" ry="${h * .045}" fill="${c}" opacity=".7"/><rect x="${w * .42}" y="${h * .13}" width="${w * .16}" height="${h * .08}" rx="2" fill="${c}"/></svg>`);
}
function sheetSVG(seed: number, w: number, h: number) {
  const c = ["#3E4A5C", "#6B4E9E", "#B0762A", "#2E6E5B"][seed % 4];
  return "data:image/svg+xml;utf8," + encodeURIComponent(`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${w} ${h}"><rect width="${w}" height="${h}" fill="#F4F6F8"/><rect x="${w * .14}" y="${h * .2}" width="${w * .62}" height="${h * .6}" fill="${c}" opacity=".85"/><rect x="${w * .2}" y="${h * .26}" width="${w * .62}" height="${h * .6}" fill="${c}" opacity=".5"/><rect x="${w * .26}" y="${h * .32}" width="${w * .62}" height="${h * .6}" fill="${c}" opacity=".28"/></svg>`);
}
export function thumb(it: { lineId: string; artSeed: number; imageUrl?: string | null }, w: number, h: number) {
  if (it.imageUrl) return it.imageUrl;
  return it.lineId === "L1" ? artSVG(it.artSeed, w, h) : it.lineId === "L2" ? drumSVG(it.artSeed, w, h) : sheetSVG(it.artSeed, w, h);
}
